"""Tests for ``fractal`` CLI."""

from .test_config_cli import *
from .test_cost_resume import *
from .test_data_cli import *
from .test_fractal_cmd import *
from .test_init_bootstrap import *
from .test_init_lock import *
from .test_iter_cost import *
from .test_lifecycle import *
from .test_lifecycle_shells import *
from .test_node_cli import *
from .test_plan_cli import *
from .test_radio_cli import *
from .test_reconcile_cli import *
from .test_regressions import *
from .test_reserve_budget import *
from .test_run_modes import *
from .test_script_behavior import *
from .test_signal_guards import *
from .test_start import *
from .test_stream import *
from .test_time_remaining import *
